# Generated by Django 4.2 on 2026-01-15 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_authority_email_notificationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('authority', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='core.authority')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authority_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authority User',
                'verbose_name_plural': 'Authority Users',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='in_progress_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last status change timestamp', null=True),
        ),
        migrations.CreateModel(
            name='IssueStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the status change')),
                ('authority_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to='core.authorityuser')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='core.issue')),
            ],
            options={
                'verbose_name': 'Issue Status Log',
                'verbose_name_plural': 'Issue Status Logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
